# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    short_url_service:
        class: AppBundle\ShortUrl\ShortUrlService
        arguments: ["@doctrine.orm.entity_manager"]
