# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    short_url_service:
        class: AppBundle\Service\ShortUrlService
        arguments: ["@doctrine.orm.entity_manager"]
    app.twig_extension.short_url_token:
        class: AppBundle\Twig\ShortUrlTokenFilter
        public: false
        tags:
            - { name: twig.extension }
